version: "3.3"
services:
  nodejs:
    container_name: nodejs
    build: .
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3900:3900'
    links:
      - mongodb
    environment:
      - dev=1
      - db_retry_time=3000
      - db_service=mongodb
      - db_port=2717
      - db_database=api
      - db_username=root
      - db_password=root
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - "2717:2717"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=api
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongodb
